@echo off
echo 启动MarCal桌面应用...
cd /d "D:\DocumentBuilder"
echo 清理进程...
taskkill /f /im node.exe /t 2>nul
taskkill /f /im electron.exe /t 2>nul
timeout /t 2 /nobreak >nul
echo 删除锁定文件...
rmdir /s /q node_modules\.electron* 2>nul
echo 重新安装Electron...
npm install electron --force
echo 启动应用...
npm run electron:dev
pause